[package]
name = "hashmap-entry-ownable"
version = "0.1.0"
authors = ["vthriller <unixway.drive+rs@gmail.com>"]
repository = "https://github.com/vthriller/hashmap-entry-ownable"
readme = "README.md"
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
